name: Flask App
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r webapp/requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest tests/

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and Start Docker Compose services
      run: docker-compose up -d --build

    - name: Push Flask app image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: marwanwalid5/financeapp:latest
        file: webapp/Dockerfile
        context: ./webapp